import { Button, Title, Text, Container, SimpleGrid, Flex, Divider, Group, Box } from '@mantine/core'
import { BrainCircuit, ChartBarStacked, ChartColumnBig, Download, File, History, Scale3d } from 'lucide-react'

const LandingPage = () => {

  const features = [
    {
      icon: <File color='#0f4736' />,
      title: "Easy File Upload",
      description: "Upload any Excel file (.xls or .xlsx) with a simple drag and drop interface.",
    },
    {
      icon: <ChartColumnBig color='#0f4736' />,
      title: "Interactive 2D Charts",
      description: "Generate beautiful, interactive 2D charts from your Excel data with customizable options.",
    },
    {
      icon: <Scale3d color='#0f4736' />,
      title: "Dynamic 3D Visualizations",
      description: "Transform your data into immersive 3D visualizations for deeper insights.",
    },
    {
      icon: <BrainCircuit color='#0f4736' />,
      title: "AI-Powered Insights",
      description: "Get smart insights and summary reports generated by AI from your uploaded data.",
    },
    {
      icon: <History color='#0f4736' />,
      title: "History Tracking",
      description: "Access your complete history of uploads and analyses from your personal dashboard.",
    },
    {
      icon: <Download color='#0f4736' />,
      title: "Export & Share",
      description: "Download your charts or share them directly with colleagues and stakeholders.",
    },
  ]

  return (
    <main className='overflow-x-hidden'>
      {/* Hero Section */}
      <section className='min-h-[80vh] bg-gradient-to-tr from-[#07271e] to-[#11543e] flex flex-col justify-center items-center space-y-8 md:space-y-12 px-4 py-16 relative overflow-hidden'>
        <h1 className='text-white text-3xl sm:text-4xl md:text-5xl lg:text-7xl text-center font-bold max-w-5xl leading-tight'>Transform Your Excel Data Into Powerful Insights</h1>
        <p className='text-gray-200 text-lg sm:text-xl md:text-2xl text-center max-w-3xl px-4'>Upload any Excel file and instantly generate interactive 2D and 3D charts with AI-powered analysis</p>
        <Button radius="md" color='#fff' size='xl'>
          <Text color='#0f4736' fw={600} size="xl">Get Started Free</Text>
        </Button>

        <Box className="absolute w-[500px] h-[500px] rounded-full bg-[#ffffff0d] -top-40 -right-40" /> 
        <Box className="absolute w-[300px] h-[300px] rounded-full bg-[#ffffff12] -bottom-20 left-50"/>
      </section>

      {/* Features Section */}
      <section className='py-12 md:py-20 px-4 bg-gray-50 flex flex-col items-center space-y-12 md:space-y-20'>
        <h2 className='text-3xl md:text-5xl font-bold text-center px-4'>Powerful Features for Data Analysis</h2>
        <div className='max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-10 px-4'>
          {features.map((feature, index) => (
            <div className='bg-white p-6 md:p-8 rounded-xl space-y-4 md:space-y-5 border border-gray-300 hover:shadow-lg transition-all' key={index}>
              <div className='size-12 md:size-16 rounded-lg bg-[#b0eacd] flex justify-center items-center'>{feature.icon}</div>
              <h3 className='text-xl md:text-2xl font-bold text-gray-800'>{feature.title}</h3>
              <p className='text-gray-600 text-sm md:text-base'>{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className='py-12 md:py-16 px-4 md:px-8 bg-gradient-to-tl from-[#07271e] to-[#11543e] text-center max-w-6xl mx-auto rounded-2xl relative my-8 md:my-12 overflow-hidden'>
        <Title mb={{ base: 12, md: 20 }} fz={{ base: "h2", md: "h1" }} order={1} className='text-white px-4'>
          Ready to Transform Your Excel Data?
        </Title>
        <Text size={{ base: "lg", md: "xl" }} mb={{ base: 24, md: 40 }} maw={700} mx="auto" color='white' px={4}>
          Join thousands of users who are already getting powerful insights from their Excel files
        </Text>
        <Button radius="md" color='#fff' size='xl'>
          <Text color='#0f4736' fw={600} size="xl">Get Started Free</Text>
        </Button>

        <Box className="absolute w-[300px] h-[300px] rounded-full bg-[#ffffff0d] -top-40 -right-20" /> 
        <Box className="absolute w-[200px] h-[200px] rounded-full bg-[#ffffff12] -bottom-20 left-50"/>
      </section>

      {/* Footer */}
      <footer className='text-white bg-[#07271e] mt-12 md:mt-20'>
        <Container size="lg" py={{ base: 40, md: 60 }} px={20}>
          <SimpleGrid cols={{ base: 1, sm: 2, md: 4 }} spacing={{ base: 20, md: 30 }}>
            <div>
              <div className='flex gap-2'>
                <ChartBarStacked color="white" size={30} />
                <Text size="lg" fw={700} mb="md">
                  Excel Analyzer
                </Text>
              </div>

              <Text size="sm" c="gray.3" mb="lg">
                Transform your Excel data into powerful insights with interactive 2D and 3D charts and AI-powered
                analysis.
              </Text>
            </div>

            <div>
              <Text fw={700} mb="md">
                Product
              </Text>
              <Flex direction="column" gap={10}>
                {["Features", "Pricing", "Testimonials", "FAQ", "Blog"].map((item) => (
                  <Text component="a" href="#" key={item} size="sm" c="gray.3" style={{ textDecoration: "none" }}>
                    {item}
                  </Text>
                ))}
              </Flex>
            </div>

            <div>
              <Text fw={700} mb="md">
                Company
              </Text>
              <Flex direction="column" gap={10}>
                {["About Us", "Careers", "Contact", "Privacy Policy", "Terms of Service"].map((item) => (
                  <Text component="a" href="#" key={item} size="sm" c="gray.3" style={{ textDecoration: "none" }}>
                    {item}
                  </Text>
                ))}
              </Flex>
            </div>

            <div>
              <Text fw={700} mb="md">
                Connect
              </Text>
              <Flex direction="column" gap={10}>
                {["Twitter", "LinkedIn", "Facebook", "Instagram", "YouTube"].map((item) => (
                  <Text component="a" href="#" key={item} size="sm" c="gray.3" style={{ textDecoration: "none" }}>
                    {item}
                  </Text>
                ))}
              </Flex>
            </div>
          </SimpleGrid>

          <Divider my={{ base: 30, md: 40 }} color="gray.8" />

          <Flex justify="space-between" align="center" wrap="wrap" gap={{ base: 12, md: 20 }} className='flex-col sm:flex-row'>
            <Text size="sm" c="gray.5" className='text-center sm:text-left'>
              © {new Date().getFullYear()} Excel Analyzer. All rights reserved.
            </Text>
            <Group gap={{ base: 12, md: 20 }} className='flex-wrap justify-center'>
              <Text component="a" href="#" size="sm" c="gray.5" style={{ textDecoration: "none" }}>
                Privacy Policy
              </Text>
              <Text component="a" href="#" size="sm" c="gray.5" style={{ textDecoration: "none" }}>
                Terms of Service
              </Text>
              <Text component="a" href="#" size="sm" c="gray.5" style={{ textDecoration: "none" }}>
                Cookie Policy
              </Text>
            </Group>
          </Flex>
        </Container>
      </footer>

    </main>
  )
}

export default LandingPage